name: theperlenpaintco
favicon: null
layout_spectrum: 0.4203465760219842
typography_spectrum: 0.8188144112937152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#84a896'
    - '#d18947'
    - '#b0703b'
    - '#cdbc94'
  brandStrength: 0.11353419721126556
  lightness: 0.08805944607593119
  saturation: 0.7254805476404727
  rhythmicContrast: 0.41286382894031703
purpose: []
